import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import productsRouter from "./products";
import storeRouter from "./store";
import settingsRouter from "./settings";
import dashboardRouter from "./dashboard";
import salesRouter from "./sales";
import ordersRouter from "./orders";
import paymentsRouter from "./payments";
import integrationsRouter from "./integrations";
import supportRouter from "./support";
import couponsRouter from "./coupons";
import aiRouter from "./ai";
import adminRouter from "./admin";
import subscriptionRouter from "./subscription";
import clientErrorsRouter from "./client-errors";
import whatsappRouter from "./whatsapp";
import unsplashRouter from "./unsplash";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/products", productsRouter);
router.use("/store", storeRouter);
router.use("/settings", settingsRouter);
router.use("/dashboard", dashboardRouter);
router.use("/sales", salesRouter);
router.use("/orders", ordersRouter);
router.use("/payments", paymentsRouter);
router.use("/integrations", integrationsRouter);
router.use("/support", supportRouter);
router.use("/coupons", couponsRouter);
router.use("/ai", aiRouter);
router.use("/admin", adminRouter);
router.use("/subscription", subscriptionRouter);
router.use("/whatsapp", whatsappRouter);
router.use("/unsplash", unsplashRouter);
router.use(clientErrorsRouter);

export default router;
