import { pgTable, text, boolean, timestamp } from "drizzle-orm/pg-core";

export const usersTable = pgTable("users", {
  id: text("id").primaryKey(),
  store_name: text("store_name").notNull(),
  owner_name: text("owner_name").notNull(),
  email: text("email").unique().notNull(),
  password_hash: text("password_hash").notNull(),
  phone: text("phone").notNull(),
  whatsapp: text("whatsapp").notNull(),
  store_slug: text("store_slug").unique().notNull(),
  store_type: text("store_type").default("celulares").notNull(),
  description: text("description").default(""),
  city: text("city").default("Rio de Janeiro"),
  state: text("state").default("RJ"),
  store_cep: text("store_cep").default(""),
  store_address: text("store_address").default(""),
  store_address_number: text("store_address_number").default(""),
  store_neighborhood: text("store_neighborhood").default(""),
  store_latitude: text("store_latitude").default(""),
  store_longitude: text("store_longitude").default(""),
  logo_url: text("logo_url").default(""),
  cover_url: text("cover_url").default(""),
  theme_primary: text("theme_primary").default("#dc2626"),
  theme_secondary: text("theme_secondary").default("#111827"),
  theme_accent: text("theme_accent").default("#ffffff"),
  plan: text("plan").default("free"),
  free_forever: boolean("free_forever").default(false),
  verified_badge: boolean("verified_badge").default(false),
  plan_started_at: timestamp("plan_started_at"),
  plan_expires_at: timestamp("plan_expires_at"),
  active: boolean("active").default(true),
  mp_access_token: text("mp_access_token"),
  mp_refresh_token: text("mp_refresh_token"),
  mp_user_id: text("mp_user_id"),
  mp_connected_at: timestamp("mp_connected_at"),
  mp_access_token_expires_at: timestamp("mp_access_token_expires_at"),
  mp_refresh_token_expires_at: timestamp("mp_refresh_token_expires_at"),
  onboarding_completed_at: timestamp("onboarding_completed_at"),
  is_open: boolean("is_open").default(true),
  store_hours: text("store_hours").default("[]"),
  delivery_fee_type: text("delivery_fee_type").default("none"),
  delivery_fee_amount: text("delivery_fee_amount").default("0"),
  created_at: timestamp("created_at").defaultNow(),
  last_login_at: timestamp("last_login_at"),
});


export type User = typeof usersTable.$inferSelect;
export type InsertUser = typeof usersTable.$inferInsert;
